name: Feature Request
title: "Feature: "
description: Suggest a new feature or enhancement
labels: enhancement
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature!

  - type: textarea
    id: description
    attributes:
      label: Feature description
      description: Describe the feature you'd like to see.
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: Explain why this feature would be useful.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Describe any alternative solutions or features you've considered.

